### ISSUE TITLE
Docs site hosting

### ISSUE THREAD

**Issue by seanwuapps** [go-components/go-components#4]

**Comment by heyokaysaturday** [comment]
Github pages? Or did anyone have a different hosting in mind?

**Comment by seanwuapps** [comment]
I've got somewhat negative exp. with GitHub pages. Netlify was a breeze to use. I'll setup an account today

**Comment by heyokaysaturday** [comment]
Yeah I use Netlify for my personal sites too :D Happy to go with that!
